### ISSUE TITLE
EDA: Delivery Person Age and Delivery Person Rating

### ISSUE THREAD

**Issue by apurvabanka** [apurvabanka/Forcaster#5]
**Observation**

- NULL values found in Delivery person age and delivery person rating.
- NULL values found in Multiple Deliveries column

**TODOS**

- [ ]  Replace NULL values for Delivery Person Age with the average. Make sure to put integer values.
- [ ]  Replace NULL values for Delivery Person Age with the average. Make sure to put float values with single decimal point.
- [ ] Replace NULL values for Multiple Deliveries with the most frequent values. The values are 0,1,2,3

Refer #4  for more details.
